post_install() {
  update-desktop-database -q /usr/share/applications 2>/dev/null || true
  update-mime-database /usr/share/mime >/dev/null 2>&1 || true
  xdg-mime default pinmark.desktop text/markdown >/dev/null 2>&1 || true
  xdg-mime default pinmark.desktop text/x-markdown >/dev/null 2>&1 || true
}

post_upgrade() {
  post_install
}

post_remove() {
  update-desktop-database -q /usr/share/applications 2>/dev/null || true
  update-mime-database /usr/share/mime >/dev/null 2>&1 || true
}
